# ABOUTME: Alertmanager configuration for VibeVoice monitoring notifications
# ABOUTME: Defines routing rules and notification channels for alerts

global:
  # Default SMTP configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@vibevoice.local'

# The directory from which notification templates are read
templates: 
- '/etc/alertmanager/templates/*.tmpl'

# The root route on which each alert enters
route:
  # Default receiver
  receiver: 'web.hook'
  
  # How long to wait before sending a notification again if it has already been sent successfully
  repeat_interval: 24h
  
  # Group by these labels
  group_by: ['alertname', 'service']
  
  # How long to initially wait to send a notification for a group of alerts
  group_wait: 10s
  
  # How long to wait before sending a notification about new alerts that are added to a group
  group_interval: 10s

  # Sub-routes
  routes:
  - match:
      service: vibevoice-fastapi
    receiver: vibevoice-alerts
    routes:
    # Critical alerts go to pager/slack
    - match:
        severity: critical
      receiver: critical-alerts
      repeat_interval: 5m
    # Warning alerts go to email/slack
    - match:
        severity: warning  
      receiver: warning-alerts
      repeat_interval: 30m

# Inhibition rules allow to mute a set of alerts given that another alert is firing
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5000/webhook'
    send_resolved: true

- name: 'vibevoice-alerts'
  # Slack integration example
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    channel: '#vibevoice-alerts'
    title: 'VibeVoice Alert'
    text: |
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Severity:** {{ .Labels.severity }}
      {{ end }}
    send_resolved: true

- name: 'critical-alerts'
  # PagerDuty integration example
  pagerduty_configs:
  - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY_HERE'
    description: 'Critical VibeVoice Alert'
    details:
      alert: '{{ .GroupLabels.alertname }}'
      service: '{{ .GroupLabels.service }}'
      summary: '{{ .CommonAnnotations.summary }}'
  
  # Also send to Slack for critical alerts
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    channel: '#vibevoice-critical'
    title: '🚨 CRITICAL: VibeVoice Alert'
    text: |
      {{ range .Alerts }}
      **CRITICAL ALERT:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Service:** {{ .Labels.service }}
      {{ end }}
    send_resolved: true

- name: 'warning-alerts'
  # Email notifications for warnings
  email_configs:
  - to: 'devops@vibevoice.local'
    subject: 'VibeVoice Warning Alert'
    body: |
      Hi team,
      
      The following warning alerts have been triggered:
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Severity: {{ .Labels.severity }}
      {{ end }}
      
      Please investigate.
      
      Best regards,
      VibeVoice Monitoring